import type { Metadata } from "next";
import { Figtree, Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import { NextIntlClientProvider } from "next-intl";
import { Toaster } from "@/components/ui/sonner";

const figTree = Figtree({
  variable: "--font-figtree",
  subsets: ["latin"]
})

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${figTree.variable} ${poppins.variable} antialiased`}
      >
        <NextIntlClientProvider>
          <main className="flex flex-col min-h-screen">
            {children}
            <Navbar />
            <Toaster position="top-center" />
          </main>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
